#!/bin/bash -o errexit

OCM_TOKEN=$(ocm token) 

ocmcurl() { curl -s -H "Authorization: Bearer ${OCM_TOKEN}" "https://api.openshift.com/api/assisted-install/v2/$1"; }

sayAndWait() { echo -e "$@\n-->\n" ; read -N 1 -s; }

demo() {
    # asciinema rec -i 0.7 -c tmux tmux-demo-2
    sayAndWait $'This demo shows how to boot a machine with a boot disk and connect it whatever assisted cluster we choose'

    sayAndWait $'It is done by booting the machine and extracting the iPXE script of a certain infra-env'

    sayAndWait $'First lets extract the infra-env id and the cluster information from api.openshift.com:
    ' $(type ocmcurl)

    # get my infra envs and cluster id
    sayAndWait $'Get my infra envs and cluster id from ocm:
    ocmcurl infra-envs | jq .[]|{id,cluster_id}'

    INFRA_ENV_ID=$(ocmcurl infra-envs | jq -r .[].id)
    CLUSTER_ID=$(ocmcurl infra-envs | jq -r .[].cluster_id)

    sayAndWait "infra env id: $INFRA_ENV_ID\ncluster id: $CLUSTER_ID\n"

    sayAndWait $'Show cluster has no hosts 
    ocmcurl clusters/${CLUSTER_ID} | jq \'.hosts[]\''

    ocmcurl clusters/${CLUSTER_ID} | jq '.hosts'

    # in linode, 
    # - show the uploaded image
    
    sayAndWait $'Check out linode-cli images list | grep assisted-bootloader'

    # - create a linode from the bootloader disk
    sayAndWait $'Boot a linode from the assisted-bootloader'

    # - show how to boot the machine from the disk
    # - show both LISH and GLISH console 
    # - show how the host is booting into the infra env

    sayAndWait $'Examine the cluster hosts again - ocmcurl clusters/${CLUSTER_ID} | jq .hosts[].requestd_hostname'
    ocmcurl clusters/${CLUSTER_ID} | jq '.hosts[]|{requestd_hostname, updated_at}'

    # - further demonstration of the boot disk
    sayAndWait $'More details about the custom initramfs disk from https://github.com/rgolangh/u-root/tree/generic-hub-cluster-bootloader'
    
    #cd $(mktemp -d) && git clone https://github.com/rgolangh/u-root -b generic-hub-cluster-bootloader --depth=1 && cd u-root


    #   - add another host with that disk
    #   - stop at the shell 
    #   - show the refresh token file
    #   - show the infraenv id file
    #   - show fire the assisted-bootloader and stop at the linuxboot menu
 }


